# Form implementation generated from reading ui file 'd:\gayhub\ASimpleGPTQtDemo\SimpleGPTQtDemo\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 658)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.chatGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.chatGroupBox.setGeometry(QtCore.QRect(10, 10, 401, 611))
        self.chatGroupBox.setObjectName("chatGroupBox")
        self.chatLineEdit = QtWidgets.QLineEdit(self.chatGroupBox)
        self.chatLineEdit.setGeometry(QtCore.QRect(10, 580, 301, 21))
        self.chatLineEdit.setObjectName("chatLineEdit")
        self.chatTextEdit = QtWidgets.QTextEdit(self.chatGroupBox)
        self.chatTextEdit.setGeometry(QtCore.QRect(10, 20, 381, 551))
        self.chatTextEdit.setObjectName("chatTextEdit")
        self.chatPushButton = QtWidgets.QPushButton(self.chatGroupBox)
        self.chatPushButton.setGeometry(QtCore.QRect(320, 580, 75, 24))
        self.chatPushButton.setObjectName("chatPushButton")
        self.createImgGroupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.createImgGroupBox.setGeometry(QtCore.QRect(420, 10, 541, 581))
        self.createImgGroupBox.setObjectName("createImgGroupBox")
        self.createImgLineEdit = QtWidgets.QLineEdit(self.createImgGroupBox)
        self.createImgLineEdit.setGeometry(QtCore.QRect(10, 30, 431, 21))
        self.createImgLineEdit.setObjectName("createImgLineEdit")
        self.createImgPushButton = QtWidgets.QPushButton(self.createImgGroupBox)
        self.createImgPushButton.setGeometry(QtCore.QRect(450, 30, 75, 24))
        self.createImgPushButton.setObjectName("createImgPushButton")
        self.createImgLabel = QtWidgets.QLabel(self.createImgGroupBox)
        self.createImgLabel.setGeometry(QtCore.QRect(10, 60, 512, 512))
        self.createImgLabel.setText("")
        self.createImgLabel.setObjectName("createImgLabel")
        self.apiKeyLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.apiKeyLineEdit.setGeometry(QtCore.QRect(490, 600, 471, 21))
        self.apiKeyLineEdit.setObjectName("apiKeyLineEdit")
        self.apiKeyLabel = QtWidgets.QLabel(self.centralWidget)
        self.apiKeyLabel.setGeometry(QtCore.QRect(430, 600, 61, 16))
        self.apiKeyLabel.setObjectName("apiKeyLabel")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SimpleGPTQtDemo"))
        self.chatGroupBox.setTitle(_translate("MainWindow", "对话区"))
        self.chatPushButton.setText(_translate("MainWindow", "发送"))
        self.createImgGroupBox.setTitle(_translate("MainWindow", "图片生成区"))
        self.createImgPushButton.setText(_translate("MainWindow", "生成"))
        self.apiKeyLabel.setText(_translate("MainWindow", "API Key："))
